### ISSUE TITLE
Hey, whenever I try to change my bot's profile picture but I get this error. I did every step right. Do you know the cause?

### ISSUE THREAD

**Issue by lynztx** [fymjoshh/discord-bot-animated-pfp#1]
**Cannot connect to host i.postimg.cc:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')]**

**Comment by lynztx** [comment]
EDIT: I managed to fix it by using tenor media links.
Example:
**new_profile_pic_url = 'https://media1.tenor.com/m/zVeklcxRPXUAAAAC/sparkle-hanabi.gif'** 
You go to tenor, search for a gif, right click on the gif and copy the link of the gif!

I hope this helps anyone that gets the same error as me.

**Comment by josh2good** [comment]
> **Cannot connect to host i.postimg.cc:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')]**

the image might of expired make sure you put it to never expire, if it didn't work then try the other host instead ( the one i use mostly ) but anything that can host an image and copy as image address should work. 

( i know you did figure it out this comment/reply is for other people who need help. )
